name: base_project_pelatihan_mobile_intermediate_polindra
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.2
#  Debugging (Alternative Print)
  logger: ^2.3.0
#  REACTIVE UI
  get: 4.6.6
  rxdart: 0.27.7
#  PARSING DATA FROM API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
#  SQLITE & Drift
  drift: ^2.23.1
  drift_flutter: ^0.1.0
#
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#  SQLITE & Drift
  drift_dev: ^2.23.1

#  Parsing data from API (Auto Generate Model Class)
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.8
  json_serializable: ^6.6.2

flutter:
  generate: true
  uses-material-design: true
